#cloud-config
users:
- name: ${user}
  passwd: "${passwd}"
  ssh_authorized_keys:
%{ for key in ssh_keys ~}
  - "${key}"
%{ endfor ~}
  groups: sudo
  shell: /bin/bash
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  lock_passwd: false
%{ for u in more_users ~}
- name: ${u.name}
  passwd: "${u.passwd}"
  gecos: "${u.gecos}"
  ssh_authorized_keys:
%{ for key in u.ssh_keys ~}
  - "${key}"
%{ endfor ~}
  groups: sudo
  shell: /bin/bash
  sudo: ['ALL=(ALL) NOPASSWD:ALL']
  lock_passwd: false
%{ endfor ~}

#~ # This is not working!
#~ package_update: true
#~ packages:
  #~ ...

write_files:
- path: /root/pkgs.txt
  permissions: '0644'
  content: |
    - nginx
    - curl
    - pwgen
    - micro
    - python3-venv
    - zip
    - dos2unix
    - wget
    - ssl-cert
    - libopenscap8
    - jq

- owner: root:root
  path: /etc/ssh/sshd_config.d/casio.conf
  permissions: '0644'
  content: |
    Port 22
    Port 443
    AllowTcpForwarding yes
    X11Forwarding yes

- path: /etc/networkd-dispatcher/routable.d/10-set-dns-search
  permissions: '0755'
  content: |
      #!/bin/sh
      # networkd-dispatcher sets $IFACE automatically for the interface changing state
      #
      # We only care about physical interfaces, not loopback
      if [ "$IFACE" = "lo" ]; then
        exit 0
      fi
      # Apply the search domain to whatever interface just became routable
      resolvectl domain "$IFACE" "${dns_zone}"
- path: /root/hardening
  permissions: '0755'
  content: "${hardening}"
  encoding: gz+b64

runcmd:
- sed -i~ -e 's/^127\.0\.0\.1\s*.*$/127.0.0.1 localhost '$(uname -n)'/' /etc/hosts
# We need to do this as cloud-init is ignore package installations
- apt-get update -y
- "DEBIAN_FRONTEND=noninteractive apt-get install -y $(sed -e 's/#.*//' -e 's/^ *- / /' /root/pkgs.txt)"

# Install CES agent
- >
    cd /usr/local &&
    curl -k -O https://uniagent-eu-de.obs.eu-de.otc.t-systems.com/package/agent_install.sh &&
    bash agent_install.sh
    -r eu-de -u 0.1.9 -t 2.7.2
    -o otc.t-systems.com
    -d agent.ces.${region}.otc.t-systems.com
- service sshd restart
# Run hardening script
- bash /root/hardening
