#!/bin/sh
#
# Clean-up only things that needs clean-up
#
tf=$(dirname "$0")/tf


$tf destroy \
    -target=module.vpn \
    -target=module.datastore \
    -target=module.bastion \
    -target=module.apps \
    -target=module.frontend \


